2.8 staff authorization
elias-carlson/Nokia3310-DAT257 pull request #45
Opened 2021-05-13 13:53 UTC by erikwessman

- Added log in button
- Backend creates JWT on successful login
- JWT is sent up to user, stored in local browser storage
- JWT is then used to verify employees when on /bookings page (if someone accesses /bookings without logging in, redirects to front page)
- Added log out button that removes JWT from storage and redirects to front page
- Removed See Bookings button

OBS!!! Lägg till 'BookingAppPassword' som en miljövariabel innan ni använder! Lösenordet kan vara vad som helst

2021-05-13 13:56 UTC, Elias-Hallberg reviewed
Tänk på att lägga till 'BookingAppPassword' som en användarvariabel.

2021-05-13 14:47 UTC, elias-carlson commented
Går inte att fixa så man inte behöver hålla på med systemvariabler eller? Tänker generellt sett är det ganska jobbigt och ifall dom behöver byta lösenord eller så

2021-05-14 07:36 UTC, elias-carlson requested changes
Funkar inte att logga in, får detta som URL när jag försöker också... http://localhost:3000/?password=hej

Edit: Funkar när man klickar på knappen men inte om man klickar Enter

2021-05-15 13:50 UTC, elias-carlson approved these changes
Riktigt snyggt!

2021-05-15 13:51 UTC, merged